<?php

namespace Media\TravelBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CinemaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CinemaRepository extends EntityRepository
{
}
